### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by omnomagonz** [omnomagonz/board#2]
- [ ] Count replies within a thread
- [ ] Display reply count at parent level
- [ ] Username link to public profile
- [ ] Move "Board" view to public, unauthorized
- [ ] Lock down permissions for creating threads or replies
- [ ] Public, non-authed users can view threads and contents
- [ ] Stats on main board page (# posts, threads, users)
